### ISSUE TITLE
企业版安装完成后无法登陆后台管理系统

### ISSUE THREAD

**Issue by xuanyuanaosheng** [op-sec-team/releases-openstar-Enterprise#2]
https://github.com/starjun/openstar/issues/54 

1.  企业版本搭建了，按照： https://www.kancloud.cn/openstar/install/1136672 进行了安装，日志显示安装成功：
![image](https://user-images.githubusercontent.com/4197714/126593343-f750df34-d4b6-47f3-9a91-725a7af949e8.png)

![image](https://user-images.githubusercontent.com/4197714/126594464-5b85cbc6-0102-4d1d-b265-7ba65a071337.png)

但是使用 IP:5460 无法登陆后台的管理页面，请问怎么排查下？

2.   能否提供下微信群？

**Comment by xiangys0134** [comment]
http://8.130.117.30:5460/api/test/hash_t?str=fdsafdsafsdafsad 我部署完了之后密码却修改不了。
{"msg":"week password , pls change your psd","str":"fdsafdsafsdafsad","code":"error"}

**Comment by starjun** [comment]
改个强密码
